//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinNote.Model.Entity.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotepadCategoryChanged
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string CategoryName { get; set; }
        public int ServerId { get; set; }
        public string Created { get; set; }
        public string Value { get; set; }
    }
}
